config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "documents#index"
  resources :documents, except: [:show] do
    post "top/:input_id", to: "documents#input_move_top"
    post "up/:input_id", to: "documents#input_move_up"
    post "down/:input_id", to: "documents#input_move_down"
    post "bottom/:input_id", to: "documents#input_move_bottom"
    delete ":input_id", to: "documents#input_destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
    has_one_attached :output
    has_many_attached :inputs
    has_many :sorted_inputs, -> { where(name: "inputs").order(position: :asc) }, class_name: "ActiveStorage::Attachment", as: :record, inverse_of: :record, dependent: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require 'securerandom'

  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :set_document_and_input, only: [:input_move_top, :input_move_up, :input_move_down, :input_move_bottom, :input_destroy]
  after_action :convert, only: [:create, :update, :input_move_top, :input_move_up, :input_move_down, :input_move_bottom, :input_destroy]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    
    if @document.save
      redirect_to edit_document_path(@document), notice: 'Document was successfully created.'
    else
      render :new 
    end
  end

  def update
    if @document.update(document_params)
      redirect_to edit_document_path(@document), notice: 'Document was successfully updated.' 
    else
      render :edit 
    end
  end

  def destroy
    @document.inputs.purge_later
    @document.destroy

    redirect_to documents_url, notice: 'Document was successfully destroyed.'
  end

  def input_move_up
    @input.move_higher
    redirect_to edit_document_path(@document)
  end

  def input_move_top
    @input.move_to_top
    redirect_to edit_document_path(@document)
  end

  def input_move_down
    @input.move_lower
    redirect_to edit_document_path(@document)
  end
  
  def input_move_bottom
    @input.move_to_bottom
    redirect_to edit_document_path(@document)
  end

  def input_destroy
    @input.purge
    redirect_to edit_document_path(@document)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    def set_document_and_input
      @document = Document.find(params[:document_id])
      @input = ActiveStorage::Attachment.find(params[:input_id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:name, inputs: [])
    end

    def convert
      output_tmp_name = "/tmp/#{SecureRandom.hex}.pdf"

      docs_to_glue = DocumentsHelper.create_tmp_files(@document.sorted_inputs)
  
      DocumentsHelper.create_output_file(docs_to_glue, output_tmp_name)
  
      @document.output.attach(io: File.open("#{output_tmp_name}"), filename: "#{@document.name}.pdf")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper

    def self.create_tmp_files(inputs)
        docs_to_glue = ""

        inputs.each do | input | 
            tmp_name = "/tmp/#{SecureRandom.hex}"

            File.open(tmp_name, 'wb') do |file|
                file.write(input.download)

                docs_to_glue += " #{tmp_name}"
        
                if (input.filename.to_s.split('.').last != "pdf")
                    DocumentsHelper.convert_to_pdf(tmp_name)
                    docs_to_glue += ".pdf" # Add .pdf to filename in case it was converted
                end
            end 
        end
        
        return docs_to_glue
    end

    def self.create_output_file(input_string, output_string)
        %x(pdfunite #{input_string} #{output_string}) 
    end

    def self.convert_to_pdf(filename)
        %x(convert #{filename} #{filename}.pdf)
    end
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :inputs %>
    <%= form.file_field :inputs, multiple: true, accept: "application/pdf, image/jpeg, image/png", class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= link_to 'Back', documents_path %>

<%= render 'form', document: @document %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="5">Controls</th>
    </tr>
  </thead>

  <tbody>
    <% @document.sorted_inputs.each do |input| %>
      <tr>
        <td><%= input.blob.filename %></td>
        <td><%= link_to '', "/documents/#{@document.id}/top/#{input.id}", data: {"turbo-method": :post}, class: "gg-arrow-long-up-l", title: "Move top" %></td>
        <td><%= link_to '', "/documents/#{@document.id}/up/#{input.id}", data: {"turbo-method": :post}, class: "gg-arrow-long-up", title: "Move higher" %></td>
        <td><%= link_to '', "/documents/#{@document.id}/down/#{input.id}", data: {"turbo-method": :post}, class: "gg-arrow-long-down", title: "Move lower" %></td>
        <td><%= link_to '', "/documents/#{@document.id}/bottom/#{input.id}", data: {"turbo-method": :post}, class: "gg-arrow-long-down-l", title: "Move bottom" %></td>
        <td><%= link_to '', "/documents/#{@document.id}/#{input.id}", data: { "turbo-confirm": 'Are you sure?', "turbo-method": :delete }, class: "gg-trash", title: "Delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/index.html.erb
<h1>Documents</h1>

<%= link_to 'New Document', new_document_path %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= link_to 'Output', rails_blob_url(document.output),  target: :_blank %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Delete', document, data: { "turbo-confirm": 'Are you sure?', "turbo-method": :delete } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

<div class="center">
  <%= link_to "Download", rails_blob_url(@document.output), class: "btn btn-primary btn-block" %>
</div>

<embed src="<%= rails_blob_path(@document.output, disposition: :inline) %>" type="application/pdf" width="100%" height="600px" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pdfglue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://css.gg/css?=|arrow-long-down-l|arrow-long-down|arrow-long-up-l|arrow-long-up|trash" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <%= yield %>
  </body>
</html>